apiVersion: apps/v1
kind: Deployment
metadata:
  name: 1152187139-deployment
  labels:
    app: 1152187139
spec:
  replicas: 2
  selector:
    matchLabels:
      app: 1152187139
  template:
    metadata:
      labels:
        app: 1152187139
    spec:
      containers:
      - name: mi-contenedor
        image: 047719650114.dkr.ecr.us-east-1.amazonaws.com/j1152187139
        ports:
        - containerPort: 5000