apiVersion: v1
kind: Service
metadata:
  name: nodeport-1152187139
spec:
  type: NodePort
  selector:
    app: jam-1152187139
  ports:
    # Por defecto y por comodidad, el `TargetPort` tiene el mismo valor que el campo `port.
    - port: 80
      targetPort: 5000
     